version: '3.3'

services:
  postgres-coursework-db:
    image: 'postgres:12.0'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hibernate
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hibernate-db
volumes:
  postgres-data:

networks:
  hibernate-db:
    external: true
