server:
  port: 8080
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL94Dialect
  show_sql: true
datasource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/hibernate
  username: postgres
  password: postgres
spring:
  jpa:
    #optional - show SQL statements in console.
    show-sql: true
    properties:
      javax:
        persistence:
          sharedCache:
            #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
            mode: ALL
      hibernate:
        jdbc:
          batch_size: 5
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        #optional - enable SQL statements formatting.
        format_sql: true
        #optional - generate statistics to check if L2/query cache is actually being used.
        generate_statistics: true
        cache:
          #required - turn on L2 cache.
          use_second_level_cache: true
          #optional - turn on query cache.
          use_query_cache: true
          region:
            #required - classpath to cache region factory.
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory





